plugins {
    id 'pl.allegro.tech.build.axion-release' version '1.15.1'
    id 'biz.aQute.bnd.builder' version "$bndVersion" apply false
    id 'com.vanniktech.maven.publish' version '0.29.0' apply false
}

scmVersion {
    tag {
        prefix = 'ical4j-integration-'
    }
    versionCreator 'versionWithBranch'
    branchVersionCreator = ['master': 'simple']
    nextVersion {
        suffix = 'pre'
        separator = '-'
    }
}

configure(subprojects) {
    apply plugin: 'java-library'
    apply plugin: 'groovy'
    apply plugin: 'biz.aQute.bnd.builder'
    apply plugin: 'com.vanniktech.maven.publish'

    repositories {
        mavenCentral()
        mavenLocal()
        maven {
            url 'https://central.sonatype.com/repository/maven-snapshots/'
        }
    }

    group = 'org.ical4j'
    description = '''\
iCalendar support for integration architectures like Apache Camel
'''
    version = rootProject.scmVersion.version

    ext {
        isReleaseVersion = !version.endsWith("SNAPSHOT")
    }

    java {
        sourceCompatibility = 11
        targetCompatibility = 11
    }

    dependencies {
        api libs.ical4j, libs.ical4j.vcard

        implementation "commons-io:commons-io:$commonsIoVersion"

        annotationProcessor 'org.osgi:osgi.core:8.0.0',
                'org.osgi:org.osgi.service.component.annotations:1.5.0',
                'org.osgi:org.osgi.service.metatype.annotations:1.4.1',
                'org.osgi:org.osgi.annotation:6.0.0'

        testImplementation libs.groovy

        testImplementation platform(libs.spock.bom), libs.spock.core,
                libs.log4j.core, libs.log4j.slf4j2

        // testcontainers
        testImplementation "org.testcontainers:testcontainers:$testcontainersVersion",
                "org.testcontainers:spock:$testcontainersVersion"

    }

    jar {
        manifest {
            attributes (
                    'Implementation-Title': 'iCal4j Integration',
                    'Implementation-Version': version,
                    'Implementation-Vendor': 'Ben Fortuna'
            )
        }
    }

    test {
        useJUnitPlatform()
    }

    javadoc {
        // External javadoc links are fetched at build time and 'latest' redirects can 404 on
        // package-list, which would otherwise fail the publish. Don't let flaky link resolution
        // (or stray @link warnings) break the build.
        failOnError = false
        if (JavaVersion.current().isJava8Compatible()) {
            options.addStringOption('Xdoclint:none', '-quiet')
        }
        options {
            links 'https://docs.oracle.com/en/java/javase/11/docs/api/',
                    'https://javadoc.io/doc/org.mnode.ical4j/ical4j/latest',
                    'https://javadoc.io/doc/org.mnode.ical4j/ical4j-vcard/latest',
                    'https://javadoc.io/doc/com.sun.mail/jakarta.mail/latest'
        }
    }

    // Publishing to the Sonatype Central Portal is configured via the vanniktech plugin.
    // Host, auto-release and signing toggles live in gradle.properties
    // (SONATYPE_HOST, SONATYPE_AUTOMATIC_RELEASE, RELEASE_SIGNING_ENABLED).
    // Credentials and the signing key are supplied via ORG_GRADLE_PROJECT_* env vars in CI.
    mavenPublishing {
        coordinates(group.toString(), project.name, version.toString())

        pom {
            name = project.name
            description = 'iCalendar support for integration architectures like Apache Camel'
            url = 'http://ical4j.github.io'

            licenses {
                license {
                    name = 'iCal4j - License'
                    url = 'https://raw.githubusercontent.com/ical4j/ical4j/master/LICENSE'
                    distribution = 'repo'
                }
            }

            developers {
                developer {
                    id = 'fortuna'
                    name = 'Ben Fortuna'
                }
            }

            scm {
                url = 'https://github.com/ical4j/ical4j-integration'
                connection = 'scm:git@github.com:ical4j/ical4j-integration.git'
                developerConnection = 'scm:git@github.com:ical4j/ical4j-integration.git'
            }
        }
    }
}
